image: hvnsweeting/docker_pip3

before_script:
  - pip install -r requirements-test.txt
stages:
  - style
  - test
  - linting # latest stage because this is BETA, and just a plus for student

check_pep8:
  stage: style
  script:
    - cd /builds/pyfml/pyfml && make style

unittest:
  stage: test
  script:
    - cd /builds/pyfml/pyfml && make test

pylint:
  stage: linting
  script:
    - cd /builds/pyfml/pyfml && make lint
