image: hvnsweeting/docker_pip3

before_script:
  - pip install -r requirements-test.txt
stages:
  - style
  #- linting
  - test

check_pep8:
  stage: style
  script:
    - cd /builds/pyfml/pyfml && make style

unittest:
  stage: test
  script:
    - cd /builds/pyfml/pyfml && make test
